<template><h1 id="v2-3-0-breakpoint-slots-for-the-mqlayout-component" tabindex="-1"><a class="header-anchor" href="#v2-3-0-breakpoint-slots-for-the-mqlayout-component" aria-hidden="true">#</a> v2.3.0 Breakpoint slots for the <code>MqLayout</code> component</h1>
<p>In addition to the mq=&quot;sm&quot; property on the component, you can now also use breakpoint slots which can combine with Transition Groups for more powerful and complex renderings.</p>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mq-layout</span> <span class="token attr-name">group</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span> <span class="token attr-name">#sm</span><span class="token punctuation">></span></span>For small screens only<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span> <span class="token attr-name">#md-xl</span><span class="token punctuation">></span></span>For medium to extra-large screens only<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span> <span class="token attr-name"><span class="token namespace">#sm:</span>2</span><span class="token punctuation">></span></span>Another slot for small screens only<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span> <span class="token attr-name">#lg-</span><span class="token punctuation">></span></span>For large and smaller screens<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>mq-layout</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div></template>
